"Add About and Contact components with routing and styling"
mehul-m-prajapati/github_tracker pull request #25
Opened 2024-11-15 17:36 UTC by Abhinav8639

### Related Issue
- Closes: #<issue number>

---

### Description

---

### How Has This Been Tested?

---

### Screenshots (if applicable)

---

### Type of Change

- [ ] Bug fix
- [ v] New feature
- [ ] Code style update
- [ ] Breaking change
- [ ] Documentation update

2024-11-15 17:59 UTC, mehul-m-prajapati commented
@Abhinav8639 : Remove html pages from public folder. It should be there in pages directory only

2024-11-15 18:06 UTC, yashksaini-coder requested changes
@Abhinav8639 please complete the requested changes, and make sure to add proper issue number next time, in the PR description.

2024-11-15 18:06 UTC, yashksaini-coder commented on src/pages/Home/About.jsx
> +    <div className="about-container">
Use tailwind css classes & remove the css files

2024-11-15 18:06 UTC, yashksaini-coder commented on src/pages/Home/Contact.jsx
> +  const [form, setForm] = useState({ name: '', email: '', message: '' });
Use tailwind css classes & remove the css files

2024-11-15 18:06 UTC, yashksaini-coder commented on public/contact.html
> +<html>
Remove this duplicate contact html page @Abhinav8639

2024-11-15 18:06 UTC, yashksaini-coder commented on public/about.html
> +    <title>About</title>
Remove this duplicate about html page @Abhinav8639

2024-11-15 18:06 UTC, yashksaini-coder commented on src/pages/Home/About.css
> +  .hero {
Remove the css file @Abhinav8639

2024-11-15 18:06 UTC, yashksaini-coder commented on src/pages/Home/Contact.css
> +  .contact-methods {
Remove this css file @Abhinav8639

2024-11-15 18:06 UTC, yashksaini-coder commented on app.js
> +
Don't update this file, remove the changes from this

2024-11-16 02:53 UTC, Abhinav8639 commented on app.js
> +
hello, you mentioned not to modify the app.js file. I wanted to clarify how you'd like me to proceed with implementing the routing or features for the Contact and About pages. Should I create a new file for the routes or features, or should they be handled in a different way?

2024-11-16 03:06 UTC, mehul-m-prajapati commented on app.js
> +
@Abhinav8639 : app.js was an old implementation. I have removed it. Routing is done App.jsx only. Your changes are good in that file

2024-11-16 05:02 UTC, ZeDD0405 commented
Related Issue
- Closes: Add About Us, Contact Us pages #6

Description
- Created about.html and contact.html pages with responsive designs.
- Designed and implemented hover and shadow effects for navigation links and section headings.
- Ensured navigation between the About Us and Contact Us pages works seamlessly.
- Added CSS styling for the About and Contact sections to match the overall theme and design.
- Included form elements in the Contact Us page with interactive features such as hover effects on form fields and buttons.
- Tested for responsiveness on both desktop and mobile views, ensuring a consistent user experience across different devices.

How Has This Been Tested?
- Verified functionality by opening the pages in the browser and testing navigation between pages.
- Checked hover effects, shadow effects, and form interactions on both About and Contact pages.
- Ensured the design is responsive by resizing the browser window to confirm proper layout adjustments on various screen 
   
![Vite + React - Google Chrome 16-11-2024 10_31_58](https://github.com/user-attachments/assets/b985e8a2-0191-4b98-851a-ed923fb5e3ae)
![Vite + React - Google Chrome 16-11-2024 10_32_01](https://github.com/user-attachments/assets/b6112894-8aba-4237-8304-8b6082261925)
![Vite + React - Google Chrome 16-11-2024 10_32_04](https://github.com/user-attachments/assets/59d633e3-5275-4cea-b56b-d8662805a1d5)
sizes.

2024-11-16 09:53 UTC, yashksaini-coder requested changes
@mehul-m-prajapati there are still many things that are not correct, please fix them and raise a new PR properly.

2024-11-16 09:53 UTC, yashksaini-coder commented on app.js
> +const PORT = 3000;
As Mehul sir said previously, remove this file. We don't need this file.

2024-11-16 09:53 UTC, yashksaini-coder commented on src/pages/About/About.jsx
> +            <h3 className="font-semibold mt-4">Simple Issue Tracking</h3>
@mehul-m-prajapati sir is it okay to store this About.jsx page in another dir just for this single page. 

Same goes for Contact.jsx page

2024-11-16 09:53 UTC, yashksaini-coder commented on src/App.jsx
> +>>>>>>> da11d282ff2b82196d95284949aed1f8fa36f56a
Why is this showing here @Abhinav8639

2024-11-16 09:53 UTC, yashksaini-coder commented on src/components/Navbar.jsx
>          {/* Links/Buttons */}
The file is wrong please review your code, there are merge headers in the file

2024-11-16 10:16 UTC, Abhinav8639 commented on src/components/Navbar.jsx
>          {/* Links/Buttons */}
something gone wrong and files got replaced i will correct it

2024-11-16 10:22 UTC, closed without merging