Added the icon and title to the site
mehul-m-prajapati/github_tracker pull request #56
Opened 2024-12-05 01:05 UTC by parassareen4

### Related Issue
- Closes: #5 

---

### Description

---

### How Has This Been Tested?

---

### Screenshots (if applicable)

---

### Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Code style update
- [ ] Breaking change
- [ ] Documentation update

2024-12-05 03:31 UTC, mehul-m-prajapati commented
@parassareen4 : use a proper commit message.

2024-12-05 04:10 UTC, parassareen4 commented
> @parassareen4 : use a proper commit message.

for sure, my bad

2024-12-05 04:47 UTC, parassareen4 commented
signup is on /signup route and login on /login

2024-12-05 06:41 UTC, yashksaini-coder requested changes
Change the icon file name

2024-12-05 06:41 UTC, yashksaini-coder commented on backend/server.js
> +app.use(cors('*'));
Clean code +1

2024-12-05 06:41 UTC, yashksaini-coder commented on index.html
> +    <link rel="icon" type="image/svg+xml" href="/crl-icon.png" />
Could rename the icon file name +1

2024-12-05 06:41 UTC, yashksaini-coder commented on src/Routes/Login/Login.tsx
> +import { useNavigate } from "react-router-dom"; // Import the hook for navigation
Login Page Good +1

2024-12-05 06:41 UTC, yashksaini-coder commented on src/Routes/Router.tsx
> +      <Route path="/login" element={<Login />} />
Proper routes setup +1

2024-12-05 06:41 UTC, yashksaini-coder commented on src/Routes/Signup/Signup.tsx
> +  username: string;
Signup Page +1

2024-12-05 06:41 UTC, yashksaini-coder commented on src/components/Navbar.tsx
> +          <img src="/crl-icon.png" alt="CRL Icon" className="h-8 mr-2" />
Renamed the icon file +1

2024-12-05 13:00 UTC, parassareen4 commented on index.html
> +    <link rel="icon" type="image/svg+xml" href="/crl-icon.png" />
for sure, everything else looks good?

2024-12-06 00:00 UTC, mehul-m-prajapati requested changes

2024-12-06 00:00 UTC, mehul-m-prajapati commented on src/Routes/Signup/Signup.tsx
> +        "http://localhost:5000/api/auth/signup", // Backend endpoint
@parassareen4 : Use env var. We do not want to hard card code backend URL

2024-12-06 06:33 UTC, yashksaini-coder commented on index.html
> +    <link rel="icon" type="image/svg+xml" href="/crl-icon.png" />
yes everything else is fine, but use env vars for login auth variable @parassareen4

2024-12-06 06:35 UTC, yashksaini-coder commented on .env.example
> +VITE_BACKEND_URL=http://localhost:5000
set up PORT var, that will be assigned once the server is started using nodemon. That's the approach @mehul-m-prajapati requires

2024-12-15 04:07 UTC, parassareen4 reviewed
any changes needed here?

2024-12-15 04:07 UTC, parassareen4 commented on index.html
> +    <link rel="icon" type="image/svg+xml" href="/crl-icon.png" />
what should i change the file name to?

2024-12-15 04:07 UTC, parassareen4 commented on src/Routes/Router.tsx
> +      <Route path="/login" element={<Login />} />
how do you want the routing to be?
if you can provide a basic structure that would be very helpful

2024-12-15 04:07 UTC, parassareen4 commented on src/Routes/Signup/Signup.tsx
> +        "http://localhost:5000/api/auth/signup", // Backend endpoint
done, check it out

2024-12-15 04:07 UTC, parassareen4 commented on .env.example
> +VITE_BACKEND_URL=http://localhost:5000
in frontend? should i default it to http://localhost:5000?
currently i picked up the approach which was in backend by giving .env.example

2024-12-15 06:34 UTC, yashksaini-coder commented
> any changes needed here?

@parassareen4 good all changes look fine to me, @mehul-m-prajapati please look into this PR. I think it's good enough to be merged now.

2024-12-17 10:56 UTC, yashksaini-coder commented
@mehul-m-prajapati Kindly merge this PR

2024-12-17 16:11 UTC, mehul-m-prajapati commented
@yashksaini-coder : okay, I will test and merge today.

2024-12-21 21:32 UTC, parassareen4 commented
> @yashksaini-coder : okay, I will test and merge today.

the tests went fine?

2024-12-26 05:05 UTC, parassareen4 commented
> @yashksaini-coder : okay, I will test and merge today.

@mehul-m-prajapati i think this can be merged

2025-01-15 04:08 UTC, merged